on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master

    - name: Update SHA
      run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/_meta

    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show k8s-1-15-9-do-0-nyc1-1584253459791 > $GITHUB_WORKSPACE/.kubeconfig

    - name: Helm init 
      run: helm init --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig --upgrade 
    
    - name: Helm service account 
      run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller 2>&1
    
    - name: create ns 
      run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig create  ns mysql
    
    - name: install operators
      run: helm install $GITHUB_WORKSPACE/charts/mysql-operator/ --name mysql-operator --namespace mysql --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig
       
#     - name: Deploy to DigitalOcean Kubernetes
#       run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig apply -f $GITHUB_WORKSPACE/config/deployment.yml

#     - name: Verify deployment
#       run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig rollout status deployment/static-example
